name: viber-unofficial
version: '0.1' 
summary: Unofficial snap for Viber Desktop
description: |
  Viber is a calling and messaging app that connects people–no matter who they are, or where they’re from.
  With a free and secure connection, over 1 billion users worldwide communicate with their loved ones 
  through high-quality audio and video calls, messaging, and much more. All Viber calls and chats are
  protected by built-in end-to-end encryption, so you can be sure that your conversations are always secure.

grade: stable
confinement: strict

parts:
  viber:
    plugin: dump
    source: http://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
    source-type: deb
    after: [desktop-glib-only]
    stage-packages:
      - libxss1
      - libssl1.0.0
      - libpulse0
      - libpulse-mainloop-glib0
      - libasound2
      - libnss3
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libcurl3
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libsm6
      - libxi6
      - libxtst6
      - libxrandr2
      - libegl1-mesa
      - libxcb-xkb1
      - libxcb-render-util0
      - libxcb-xfixes0
      - libxcb-randr0
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-icccm4
      - libxcb-shape0
      - libxcb-util1
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-libav
apps:
  viber:
    command: desktop-launch $SNAP/opt/viber/Viber
    desktop: usr/share/applications/viber.desktop
    plugs: 
     - home
     - unity7
     - opengl
     - gsettings
     - network
     - network-bind
     - x11
     - desktop
     - desktop-legacy
     - pulseaudio
     - camera
    environment:
      DISABLE_WAYLAND: 1
      WAYLAND_DISPLAY: no-display
      QTCOMPOSE: $SNAP/usr/share/X11/locale 
